controlPlane:
  # Configure networking
  ingress:
    enabled: true
    host: sample-app-${PR_NUMBER}.mghcloud.com
    pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: "traefik"
      traefik.ingress.kubernetes.io/ssl: "true"
    spec:
      ingressClassName: traefik
      tls:
        - hosts:
            - sample-app-${PR_NUMBER}.mghcloud.com
          secretName: wildcard-mghcloud-com-tls
      rules:
        - host: sample-app-${PR_NUMBER}.mghcloud.com
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: sample-app
                    port:
                      number: 80

sync:
  toHost:
    serviceAccounts:
      enabled: true
  fromHost:
    nodes:
      enabled: true
      clearImageStatus: true
    storageClasses:
      enabled: true
      patch:
        enabled: true
        patch:
          spec:
            storageClass: nfs

exportKubeConfig:
  context: pr-${PR_NUMBER}.mghcloud.com
  server: https://vcluster-k8s-api.mghcloud.com
  secret:
    name: pr-${PR_NUMBER}.mghcloud.com-kubeconfig
